version: '2.1'

services:
  backend:
    image: backend
    build: .
    environment:
       - TYPEORM_CONNECTION=postgres
       - TYPEORM_HOST=localhost
       - TYPEORM_USERNAME=oilfox
       - TYPEORM_PASSWORD=oilfox
       - TYPEORM_DATABASE=postgres
       - TYPEORM_PORT=5432
       - TYPEORM_SYNCHRONIZE=false
       - TYPEORM_LOGGING=false
       - TYPEORM_ENTITIES=src/entity/**/*.ts
    ports:
      - 4000:4000